import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";

export default function Home() {
  const [url, setUrl] = useState("");
  const [longUrl, setLongUrl] = useState("");
  const [shortUrl, setShortUrl] = useState("");

  const changeUrl = (e: React.ChangeEvent<HTMLInputElement>): void => {
    setUrl(e.target.value);
  };

  const generateShortUrl = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault(); // Prevent form refresh

    const response = await fetch("/api/urls", {
      method: "POST",
      body: JSON.stringify({
        url: url,
      }),
    });

    if (!response.ok) {
      alert("An error occurred");
      return;
    }

    const data = await response.json();
    setUrl("");
    setLongUrl(url);
    setShortUrl(data?.shortUrlID);
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            URL Shortener
          </h1>
          <form className="flex flex-col gap-4" onSubmit={generateShortUrl}>
            <Input
              aria-label="URL"
              onChange={changeUrl}
              value={url}
              required
              type="url"
            />
            <Button type="submit">Generate</Button>
            <p className="text-white">
              {!!shortUrl &&
                `Generated short URL: ${document.location.origin}/api/urls/${shortUrl}`}
            </p>
            <p className="text-white">
              {!!shortUrl && `will redirect to: ${longUrl}`}
            </p>
          </form>
        </div>
      </main>
    </>
  );
}
